name: app_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  intl: ^0.20.0

  # internal
  app_models: ^1.0.0
  app_services: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
