name: sbccapp
description: "A new Flutter project."
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  intl: ^0.20.0
  device_preview: ^1.2.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  get_it: ^8.0.0
  rxdart: ^0.28.0
  uuid: ^4.3.3
  provider: ^6.0.5
  get: ^4.7.2
  dio: ^5.9.0
  connectivity_plus: ^6.0.0
  jiffy: ^6.2.1
  go_router: ^13.2.4 # stefan: reverted update to ^14.6.3 because it just silently broke navigation in onboarding, see FLTR-16209
  adaptive_chameleon_theme: ^2024.9.0
  universal_platform: ^1.0.0+1
  json_annotation: ^4.8.1
  geolocator: ^14.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geocoding: ^4.0.0
  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  flutter_svg: ^2.2.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.0
  battery_plus: ^5.0.2
  mobile_scanner: ^7.0.1
  permission_handler: ^11.3.1

  ## Internal
  app_common: ^1.0.0
  app_models: ^1.0.0
  app_services: ^1.0.0
  app_network: ^1.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  mocktail: ^1.0.0
  flutter_lints: ^5.0.0
  git: ^2.0.0
  t_stats: ^3.0.0
  file: ^7.0.0 # used in tests
  mobx_codegen: ^2.3.0
  freezed: ^2.3.5
  url_launcher: ^6.3.0
  r_flutter: #^0.9.0 # using a version from git to get the unreleased `add_file_path_comments` feature. Remove when Version 0.9.1 or later is officially released
    git:
      url: https://github.com/timfreiheit/r_flutter.git
      ref: 1a5f986d87b8cd6b8a77b470f69a9ae1d5a2ec60
  http: ^1.2.0 # used in tests
  copy_with_extension_gen: ^6.0.0
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

r_flutter:
  add_file_path_comments: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  remove_alpha_ios: true
